apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Validate=false,SkipDryRunOnMissingRessource=true
  name: example-config
data:
  # Key-value pairs
  example.property.6: "value6" 
