apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: "2025-02-04T17:47:31Z"
  labels:
    app.kubernetes.io/managed-by: openshift-git
  name: openshift-gitops-server-2
  namespace: openshift-gitops
spec:
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: openshift-gitops-server
    weight: 100
  wildcardPolicy: None
