apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secret-provider-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: vault-csi-provider
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.30.0
    helm:
      releaseName: vault
      values: |
        csi:
          enabled: true
        server:
          enabled: true
          dataStorage:
             enabled: false
        injector:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - kind: DaemonSet
    group: apps
    jsonPointers:
      - /spec/template/spec/containers/0/securityContext/privileged
