apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: demo-app
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      serviceAccountName: demo-app-sa
      containers:
        - name: app
          image: nginxinc/nginx-unprivileged:latest
          volumeMounts:
            - name: vault-secrets
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: vault-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: demo-app-creds
