apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: demo-app-creds
  namespace: demo-app
spec:
  provider: vault
  parameters:
    vaultAddress: http://vault.vault-csi-provider:8200 # <name>.<namespace>:port
    roleName: app
    objects: |
      - objectName: "demoAppUsername"
        secretPath: "secret/demo/config"
        secretKey: "username"
      - objectName: "demoAppPassword"
        secretPath: "secret/demo/config"
        secretKey: "password"
