apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-operator
  labels:
    security.openshift.io/scc.podSecurityLabelSync: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-cert-manager-operator
  namespace: cert-manager-operator
spec:
  targetNamespaces:
    - cert-manager-operator

    
    
