apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-operator
  labels:
    security.openshift.io/scc.podSecurityLabelSync: "true"
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
