apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: test-sa-gitops
imagePullSecrets:
- name: my-database-secret
- name: test-secret 
# Explicitly define the empty array so Git ([]) matches Live filtered ([])
