apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  controller:
    processors: {}
    resources:
      limits:
        cpu: '2'
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    sharding: {}
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  ha:
    enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  initialSSHKnownHosts: {}
  monitoring:
    enabled: false
  notifications:
    enabled: false
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  rbac:
    defaultPolicy: ''
    policy: |
      g, system:cluster-admins, role:admin
    scopes: '[groups]'
  redis:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  repo:
    resources:
      limits:
        cpu: '1'
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
  resourceInclusions: |
    - apiGroups:
      - ""               # Core API group
      kinds:
      - "*"
      clusters:
      - "*"
    - apiGroups:
      - "apps"
      kinds:
      - "*"
      clusters:
      - "*"
    - apiGroups:
      - "batch"
      kinds:
      - "*"
      clusters:
      - "*"
    - apiGroups:
      - "extensions"
      kinds:
      - "*"
      clusters:
      - "*"
    - apiGroups:
      - "networking.k8s.io"
      kinds:
      - "*"
      clusters:
      - "*"
    - apiGroups:
      - "rbac.authorization.k8s.io"
      kinds:
      - "*"
      clusters:
      - "*"
    - apiGroups:
      - "storage.k8s.io"
      kinds:
      - "*"
      clusters:
      - "*"
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi
    route:
      enabled: true
    service:
      type: ''
  sso:
    dex:
      openShiftOAuth: true
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi
    provider: dex
  tls:
    ca: {}
