apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    kube-burner: argocd-performance-test
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      kube-burner: argocd-performance-test
      app: nginx
  template:
    metadata:
      labels:
        kube-burner: argocd-performance-test
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bubble-animation-config
  labels:
    kube-burner: argocd-performance-test
