apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    kube-burner: argocd-performance-test
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      kube-burner: argocd-performance-test
      app: nginx
  template:
    metadata:
      labels:
        kube-burner: argocd-performance-test
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            while true; do
              for i in $(seq 1 10); do
                echo "Log line $i at $(date)"
              done
              sleep 10
            done
