apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    kube-burner: argocd-performance-test
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      kube-burner: argocd-performance-test
      app: nginx
  template:
    metadata:
      labels:
        kube-burner: argocd-performance-test
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            while true; do
              for i in $(seq 1 10); do
                echo "FAST log line $i at $(date)"
              done
              sleep 3
            done
      - name: slow-logger
        image: busybox:1.36
        command: ["/bin/sh","-c"]
        args:
          - |
            i=0
            while true; do
              i=$((i+1))
              echo "SLOW log $i at $(date)"
              sleep 15
            done
