apiVersion: nextgen.k8s.test/v1alpha1
kind: AppReplica
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: app
  namespace: argocd-0
spec:
  deploymentName: example-foo
  replicas: 2
  deploymentImage: "nginx:latest"
