apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment  # Name of the deployment
spec:
  replicas: 3  # Number of desired replicas (pods)
  selector:
    matchLabels:
      app: nginx  # Labels to match pods controlled by this deployment
  template:
    metadata:
      labels:
        app: nginx  # Labels applied to pods created by this deployment
    spec:
      containers:
      - name: nginx  # Container name
        image: docker.io/library/nginx:latest # Docker image used by the container
        ports:
        - containerPort: 80  # Port to expose on the container
