apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    kube-burner: argocd-performance-test
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      kube-burner: argocd-performance-test
      app: nginx
  template:
    metadata:
      labels:
        kube-burner: argocd-performance-test
        app: nginx
    spec:
      containers:
      - name: nginx
        image: >-
            image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest
        ports:
        - containerPort: 80
