apiVersion: apps/v1
kind: Deployment
metadata:
  name: faulty-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faulty-app
  template:
    metadata:
      labels:
        app: faulty-app
    spec:
      containers:
      - name: web
        image: nginx:does-not-exist-v99
        ports:
        - containerPort: 80
