apiVersion: batch/v1
kind: Job
metadata:
  name: post-install-job
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: hook
          image: busybox
          command: ["sh", "-c", "echo Hello from post-install hook! && sleep 5"]
      restartPolicy: Never
