# templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hook-created-sa
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
