apiVersion: batch/v1
kind: Job
metadata:
  name: vault-csi-scc-setup
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: vault-csi-setup
      restartPolicy: OnFailure
      containers:
        - name: scc-setup
          image: registry.access.redhat.com/ubi8/ubi-minimal
          command:
            - /bin/sh
            - -c
            - |
              echo "Assigning SCCs..."
              oc adm policy add-scc-to-user privileged system:serviceaccount:{{ .Release.Namespace }}:secrets-store-csi-driver-operator
              oc adm policy add-scc-to-user privileged system:serviceaccount:{{ .Release.Namespace }}:vault-csi-provider
