apiVersion: batch/v1
kind: Job
metadata:
  name: patch-vault-csi-daemonset
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: vault-csi-setup
      restartPolicy: OnFailure
      containers:
        - name: patch-vault-csi
          image: quay.io/openshift/origin-cli:4.12  # Image with `oc` binary
          command:
            - /bin/bash
            - -c
            - |
              echo "Patching Vault CSI DaemonSet to set privileged=true..."
              oc patch daemonset vault-csi-provider \
                -n {{ .Release.Namespace }} \
                --type='json' \
                --patch='[{"op": "add", "path": "/spec/template/spec/containers/0/securityContext", "value": {"privileged": true}}]'
