apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example-sts
  labels:
    app: example
spec:
  serviceName: "example-service"
  replicas: 2
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: example-pvc
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: example-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard" # Default storage class in Minikube
      resources:
        requests:
          storage: 1Gi
