apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      annotations:
      labels:
        app: demo
    spec:
      serviceAccountName: demo-app
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
        - name: app
          args: 
          - run
          - --loglevel=debug
          image: quay.io/mangaal/argocd-resource-tracker:test-v1
          volumeMounts:
            - name: 'vault-db-creds'
              mountPath: '/tmp/secrets-store'
              readOnly: true
      volumes:
        - name: vault-db-creds
          csi:
            driver: 'secrets-store.csi.k8s.io'
            readOnly: true
            volumeAttributes:
              secretProviderClass: 'demo-app-creds'
