apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: demo-app-creds
spec:
  provider: vault
  parameters:
    roleName: "app"  # Should match the Kubernetes auth role you created in Vault
    objects: |
      - objectName: "demoAppUsername"
        secretPath: "secret/webapp/config"
        secretKey: "username"
      - objectName: "demoAppPassword"
        secretPath: "secret/webapp/config"
        secretKey: "password"
