apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: demo-app-creds
  namespace: demo-app
spec:
  parameters:
    objects: |
      - objectName: "demoAppUsername"
        secretPath: "secret/demo/config"
        secretKey: "username"
      - objectName: "demoAppPassword"
        secretPath: "secret/demo/config"
        secretKey: "password"
    roleName: app
    vaultAddress: http://vault-csi-provider.vault-secret-provider-app:8200
  provider: vault
