apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: demo-app-creds
spec:
  provider: vault
  parameters:
    roleName: "app"  # Should match the Kubernetes auth role you created in Vault
    vaultAddress: "http://vault.hashicorp-vault:8200"
    objects: |
      - objectName: "demoAppUsername"
        secretPath: "secret/data/demo/config"
        secretKey: "username"
      - objectName: "demoAppPassword"
        secretPath: "ssecret/data/demo/config"
        secretKey: "password"
